version: '3.8'

services:
  web:
    build: .
    container_name: trading-web
    env_file: .env
    command: python /usr/src/trading_floor/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/trading_floor
    ports:
      - "8000:8000"
    depends_on:
      - db

  minio:
    image: minio/minio:latest
    command: server --console-address ":9004" /data
    restart: always
    ports:
      - "9000:9000"
      - "9004:9004"
    env_file: .env
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio


  db:
    image: postgres:13.10-alpine
    container_name: trading-db
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  minio_data:
  minio_config:
